# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr: none

pool:
  vmImage: vs2017-win2016

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
   