# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr: none

pool:
  vmImage: vs2017-win2016

<<<<<<< HEAD
<<<<<<< Updated upstream
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
   
=======
=======
>>>>>>> c3d4d1e25acaefb16ac0560c4a4eb8fb606a3d6c
stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - bash: echo "A1"

- stage: B
  jobs:
  - job: B1
    steps:
      - bash: echo "B1"  
<<<<<<< HEAD
  - job: B2
    steps:
      - bash: echo "B2"  
  - job: B3
    dependsOn: B1
    steps:
      - bash: echo "B3"  
     
>>>>>>> Stashed changes
=======


   
>>>>>>> c3d4d1e25acaefb16ac0560c4a4eb8fb606a3d6c
